// swift-tools-version: 6.0
import PackageDescription

// PressboardKit 1.0.0 — an iOS keyboard engine that is indistinguishable from the native one.
//
// This repository is the manifest. The engine ships as binaries, verified by the checksums
// below; the source lives in a private repository. Licence terms are in LICENSE — the engine is
// free, and registration issues the licence that unlocks it. Without one it types in English and
// does nothing else, which is a working keyboard and deliberately so.
//
// Generated by scripts/publish-release.sh. Do not edit: a URL or a checksum written by hand is
// one more thing that can disagree with the zip it names.
let package = Package(
    name: "PressboardKit",
    platforms: [.iOS("26.0")],
    products: [
        .library(name: "PressboardKit", targets: ["PressboardKit"]),
        .library(name: "PressboardKitLayouts", targets: ["PressboardKitLayouts"]),
        .library(name: "PressboardKitAutocomplete", targets: ["PressboardKitAutocomplete"]),
        .library(name: "PressboardKitEmoji", targets: ["PressboardKitEmoji"]),
        .library(name: "PressboardKitApp", targets: ["PressboardKitApp"]),
        .library(name: "PressboardKitLicensing", targets: ["PressboardKitLicensing"]),
    ],
    targets: [
        .binaryTarget(
            name: "PressboardKit",
            url: "https://github.com/PressboardKit/PressboardKit/releases/download/1.0.0/PressboardKit.xcframework.zip",
            checksum: "a4d6e4eadcca79ac03ce88bc29577e880c267f7969c4e69a1eb1404dd5560194"),
        .binaryTarget(
            name: "PressboardKitLayouts",
            url: "https://github.com/PressboardKit/PressboardKit/releases/download/1.0.0/PressboardKitLayouts.xcframework.zip",
            checksum: "0dd91bf3fc74294acb1de51d968a2e7b1a4a0d02c359da37c05ba3024b7dd51b"),
        .binaryTarget(
            name: "PressboardKitAutocomplete",
            url: "https://github.com/PressboardKit/PressboardKit/releases/download/1.0.0/PressboardKitAutocomplete.xcframework.zip",
            checksum: "3390cbfd1f20c3a2b4e4f7617925944d67ff6f469f4f7b387b5db5c2277229ec"),
        .binaryTarget(
            name: "PressboardKitEmoji",
            url: "https://github.com/PressboardKit/PressboardKit/releases/download/1.0.0/PressboardKitEmoji.xcframework.zip",
            checksum: "416f402e03a592a4d724a7eafd94c072fd5437a25f5ae34ef82c75b3b3e09a30"),
        .binaryTarget(
            name: "PressboardKitApp",
            url: "https://github.com/PressboardKit/PressboardKit/releases/download/1.0.0/PressboardKitApp.xcframework.zip",
            checksum: "a45362502ff3c3da2f07836f9930919c721c678378a05f7346750d1b6c9152e7"),
        .binaryTarget(
            name: "PressboardKitLicensing",
            url: "https://github.com/PressboardKit/PressboardKit/releases/download/1.0.0/PressboardKitLicensing.xcframework.zip",
            checksum: "1333953153c89f46b35d1078e7c2a1272b7eab08fe24f4474203c0fd02eb8b29"),
    ]
)
